apiVersion: v1
kind: ReplicationController
metadata:
 name: rc
spec:
 replicas: 3
 template:
  metadata:
   labels:
    for: nodeport  
  spec:
    containers:
     - image: nginx
       name: nginxcontainer
       ports:
        - containerPort: 80
       livenessProbe:
         httpGet:
           path: /index.html 
           port: 80  
         initialDelaySeconds: 10
         periodSeconds: 10  
