apiVersion: batch/v1
kind: CronJob
metadata:
  name: cjob-svc
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
         labels: 
          app: c-job
        spec:
         restartPolicy: OnFailure
         containers:
           - image: luksa/batch-job
             name: croncontainer

