apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobsvc
spec:
  schedule: "0 16 17 1 3"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjobpod
        spec:
          restartPolicy: OnFailure
          containers:
            - image: luksa/batch-job
              name: cjobcontainer

