apiVersion: v1
kind: Deployment
metadata:
  name: deploymentapp
spec:
  replicas: 3
  selector:
    matchLabels:
       for: clusterIP  # Updated label selector to match Service
  template:
    metadata:
      labels:
        app: devlopment # Updated label to match Service
    spec:
       containers:
         - image: nginx
           name: nginxcontainer

