apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controllerpod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:          
          httpGet: 
           path: /index.html
           port: 80
          periodSeconds: 10 
          initialDelaySeconds: 10  
