apiVersion: v1
kind: ReplicationController
metadata:
  name: rcpod
spec: 
 replicas: 3
 template:
  metadata: 
   labels: 
    app: dev
  spec:
    containers:
      - image: httpd
        name: httpdcontainer
        ports:
          - containerPort: 80



