apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentsvc
spec:
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - deploy
          - testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - image: nginx
          name: nginxcontainer
          ports:
            - containerPort: 80

